// ─────────────────────────────────────────────────────────────────────────────
// DESIGN TOKENS
// ─────────────────────────────────────────────────────────────────────────────
export const C = {
  bgDeep:"#050810", bgPanel:"#0a0f1e", bgWidget:"#0d1b2a", bgInput:"#111827",
  accent:"#00d4ff", accentDim:"rgba(0,212,255,0.4)", accentGlow:"rgba(0,212,255,0.25)",
  amber:"#f59e0b", red:"#ef4444", green:"#22c55e", dimGray:"#4b5563",
  text:"#e2e8f0", textSec:"#94a3b8", readout:"#00d4ff", deload:"#a855f7",
};

// ─────────────────────────────────────────────────────────────────────────────
// EXERCISE NAMES  (1–215)
// ─────────────────────────────────────────────────────────────────────────────
export const EXERCISE_NAMES = {
  1:"Standing Band Chest Press", 2:"Floor Band Press", 3:"Incline Band Chest Press",
  4:"Decline Band Chest Press", 5:"Single-Arm Band Chest Press", 6:"Banded Push-Up",
  7:"Archer Push-Up", 8:"Pike Push-Up with Band", 9:"Standing Band Chest Fly (Mid)",
  10:"Low-to-High Chest Fly", 11:"High-to-Low Chest Fly", 12:"Single-Arm Fly",
  13:"Band Pullover", 14:"Close-Grip Band Press", 15:"Wide-Grip Band Press",
  16:"Band Squeeze Press", 17:"Banded Dip", 18:"Svend Press with Band",
  19:"Band-Resisted Bench Press", 20:"1.5-Rep Band Press",
  21:"Standing Band Row", 22:"Seated Band Row", 23:"Bent-Over Band Row",
  24:"Single-Arm Band Row", 25:"Wide-Grip Band Row", 26:"Close-Grip Band Row",
  27:"Meadows Row", 28:"Band Lat Pulldown", 29:"Single-Arm Band Pulldown",
  30:"Straight-Arm Band Pulldown", 31:"Banded Pull-Up Assist",
  32:"Band-Resisted Pull-Up", 33:"Band Face Pull", 34:"Band Pull-Apart",
  35:"Overhead Band Pull-Apart", 36:"Y-T-W-L Raise", 37:"Band Romanian Deadlift",
  38:"Band Good Morning", 39:"Band Reverse Fly", 40:"Band Shrug",
  41:"Band Shrug with Hold", 42:"Superman with Band",
  43:"Standing Band Overhead Press", 44:"Single-Arm Overhead Press",
  45:"Arnold Press with Band", 46:"Push Press with Band", 47:"Band Front Raise",
  48:"Band Lateral Raise", 49:"Leaning Lateral Raise", 50:"Band Scaption Raise",
  51:"Band Rear Delt Fly", 52:"Band Cuban Press", 53:"Band External Rotation",
  54:"Band Internal Rotation", 55:"Band 90/90 Shoulder ER", 56:"Band Upright Row",
  57:"Band W-Raise", 58:"Band Prone I-Raise",
  59:"Kneeling Band Crunch", 60:"Standing Band Crunch", 61:"Banded Reverse Crunch",
  62:"Banded Leg Raise", 63:"Pallof Press", 64:"Pallof Press with Rotation",
  65:"Pallof Press Overhead", 66:"Woodchop (High-to-Low)",
  67:"Reverse Woodchop (Low-to-High)", 68:"Horizontal Woodchop",
  69:"Banded Dead Bug", 70:"Banded Bicycle Crunch", 71:"Banded Plank",
  72:"Banded Side Plank", 73:"Russian Twist with Band",
  74:"Tall-Kneeling Band Rotation", 75:"Banded Ab Rollout",
  76:"Banded Mountain Climber", 77:"Standing Band Lift (Low-to-High)",
  78:"Glute Bridge", 79:"Banded Hip Thrust", 80:"Single-Leg Hip Thrust",
  81:"Frog Pump", 82:"Glute Bridge March", 83:"Donkey Kick",
  84:"Donkey Kick + Pulse", 85:"Fire Hydrant", 86:"Clamshell",
  87:"Lateral Band Walk", 88:"Forward Band Walk", 89:"Monster Walk",
  90:"X-Band Walk", 91:"Standing Hip Abduction", 92:"Glute Kickback",
  93:"Curtsy Lunge", 94:"Pull-Through", 95:"Seated Hip Abduction", 96:"Hip Circle",
  97:"Band Squat", 98:"Front Squat (Band)", 99:"Goblet Squat with Band",
  100:"Sumo Squat with Band", 101:"Narrow-Stance Band Squat",
  102:"Bulgarian Split Squat", 103:"Reverse Lunge", 104:"Forward Lunge",
  105:"Walking Lunge", 106:"Lateral Lunge", 107:"Curtsy Lunge (Quads)",
  108:"Step-Up with Band", 109:"Sissy Squat with Band",
  110:"Terminal Knee Extension (TKE)", 111:"Spanish Squat",
  112:"Wall Sit with Band", 113:"Cyclist Squat (Heels Elevated)",
  114:"Box Squat with Band", 115:"Jump Squat with Band", 116:"Hack Squat with Band",
  117:"Romanian Deadlift (Band RDL)", 118:"Single-Leg RDL",
  119:"Stiff-Leg Deadlift", 120:"B-Stance RDL", 121:"Lying Leg Curl",
  122:"Seated Leg Curl", 123:"Standing Leg Curl", 124:"Nordic Curl (Band Assisted)",
  125:"Hip Hinge Pull-Through", 126:"Banded Reverse Hyper",
  127:"Good Morning", 128:"Snatch-Grip RDL",
  129:"Standing Bicep Curl", 130:"Alternating Curl", 131:"Hammer Curl",
  132:"Alternating Hammer Curl", 133:"Concentration Curl", 134:"Reverse Curl",
  135:"Drag Curl", 136:"Incline Curl", 137:"Preacher-Style Curl",
  138:"Zottman Curl", 139:"21s", 140:"Waiter's Curl",
  141:"Cross-Body Curl", 142:"Supinated Straight-Bar Curl", 143:"Spider Curl",
  144:"Triceps Pushdown", 145:"Overhead Triceps Extension",
  146:"Single-Arm Overhead Extension", 147:"Triceps Kickback",
  148:"Band Skull Crusher", 149:"Close-Grip Band Press (Triceps)",
  150:"Band Dip", 151:"Reverse-Grip Pushdown", 152:"Single-Arm Pushdown",
  153:"Diamond Push-Up with Band", 154:"Cross-Body Triceps Extension",
  155:"Tate Press with Band", 156:"JM Press with Band",
  157:"Wrist Curl", 158:"Reverse Wrist Curl", 159:"Radial Deviation",
  160:"Ulnar Deviation", 161:"Wrist Pronation", 162:"Wrist Supination",
  163:"Finger Extension", 164:"Grip Crush",
  165:"Reverse Curl (Forearm Focus)", 166:"Band Farmer's Carry Hold",
  167:"Standing Calf Raise", 168:"Seated Calf Raise", 169:"Single-Leg Calf Raise",
  170:"Donkey Calf Raise", 171:"Eccentric Calf Raise", 172:"Tibialis Raise",
  173:"Bent-Knee Calf Raise", 174:"Explosive Calf Raise",
  175:"Calf Raise with Band Assist", 176:"Seated Tibialis Raise",
  177:"Neck Flexion", 178:"Neck Extension",
  179:"Lateral Neck Flexion (Left)", 180:"Lateral Neck Flexion (Right)",
  181:"Isometric Neck Flexion Hold", 182:"Isometric Neck Extension Hold",
  183:"Chin Tuck (Neck Retraction)", 184:"Isometric Lateral Hold",
  185:"Band Deadlift", 186:"Band RDL to Row", 187:"Band Thruster",
  188:"Band Clean Pull", 189:"Band Snatch Pull", 190:"Band Swing",
  191:"Band Farmer's Carry", 192:"Band Zercher Carry",
  193:"Band Overhead Carry", 194:"Band Bear Hug Carry",
  195:"Band Push Press", 196:"Band Squat to Row",
  197:"Band Lunge to Curl", 198:"Band Halo", 199:"Band Around-the-World",
  200:"Band Woodchop Lunge", 201:"Band Deadlift + Shrug", 202:"Band Power Clean",
  203:"Hip Flexor Stretch (Band)", 204:"Hip Internal Rotation Mob",
  205:"Hip External Rotation Mob", 206:"Ankle Dorsiflexion Mob",
  207:"Shoulder Capsule Stretch", 208:"Lat Stretch with Band",
  209:"Thoracic Extension Mob", 210:"Hamstring Floss",
  211:"Quad Stretch Assist", 212:"Banded Good Morning (Stretch)",
  213:"Overhead Shoulder Mob", 214:"Wrist Flexor Stretch",
  215:"Wrist Extensor Stretch",
};

// ─────────────────────────────────────────────────────────────────────────────
// HIGH-INTENSITY TECHNIQUES
// ─────────────────────────────────────────────────────────────────────────────
export const TECHNIQUES = {
  "1_quarter_reps":       "1¼ Reps — full rep + quarter rep at peak/sticking point",
  "super_slow":           "Super Slow — 5s concentric / 5s eccentric tempo",
  "negative_accentuated": "Negative Accentuated — explosive up, 6–8s down",
  "forced_reps":          "Forced Reps — 1–2 extra reps past failure",
  "drop_set":             "Drop Set — drop to lighter band and continue to failure",
  "rest_pause":           "Rest-Pause — 12s pause then squeeze out 3–4 more reps",
  "partials":             "Partials — 6–8 partial reps in strongest range",
  "isometric_hold":       "Isometric Hold — 3s squeeze at peak each rep",
  "pre_exhaustion":       "Pre-Exhaustion — superset isolation into compound",
  "mechanical_drop_set":  "Mechanical Drop Set — shift to easier grip/stance mid-set",
};

// ─────────────────────────────────────────────────────────────────────────────
// VIDEO URLS
// ─────────────────────────────────────────────────────────────────────────────
export const VIDEOS = {
  1:"https://www.youtube.com/watch?v=6-86jEAXA08",
  2:"https://www.youtube.com/watch?v=h1uU13KkCXw",
  3:"https://www.youtube.com/watch?v=DdV5EVJBae4",
  4:"https://www.youtube.com/watch?v=4iVpEZ-Vl8U",
  5:"https://www.youtube.com/watch?v=baGx6pqU6S0",
  6:"https://www.youtube.com/watch?v=7usDIUnlfNw",
  7:"https://www.youtube.com/watch?v=r4sRk3_JxWc",
  8:"https://www.youtube.com/watch?v=6qyJNW0AuBs",
  9:"https://www.youtube.com/watch?v=Z6ly4c3YC6o",
  10:"https://www.youtube.com/watch?v=N0uLm6RT9zg",
  11:"https://www.youtube.com/watch?v=Qp0kFogluvw",
  12:"https://www.youtube.com/watch?v=-Xk7FJd51gI",
  13:"https://www.youtube.com/watch?v=I3b8FyV9vZQ",
  14:"https://www.youtube.com/watch?v=Q-lnd6SWR5A",
  15:"https://www.youtube.com/watch?v=Q-lnd6SWR5A",
  16:"https://www.youtube.com/shorts/ZwRX_f1ZvxI",
  17:"https://www.youtube.com/watch?v=mx5UJjeGdVs",
  18:"https://www.youtube.com/watch?v=0J2gScVrAA4",
  19:"https://www.youtube.com/watch?v=j7_5RxYIXPc",
  20:"https://www.youtube.com/watch?v=0J2gScVrAA4",
  21:"https://www.youtube.com/watch?v=46LmoouvP34",
  22:"https://www.youtube.com/watch?v=eOKwM5nHzj4",
  23:"https://www.youtube.com/watch?v=Y3H17rshgZE",
  24:"https://www.youtube.com/watch?v=OvPHAdtKtHk",
  25:"https://www.youtube.com/watch?v=44d-eYe8QBs",
  26:"https://www.youtube.com/watch?v=46LmoouvP34",
  27:"https://www.youtube.com/watch?v=Z1DrxG0nSOU",
  28:"https://www.youtube.com/watch?v=84D8bVJWB3s",
  29:"https://www.youtube.com/watch?v=M_tk7gXDxdU",
  30:"https://www.youtube.com/watch?v=K4VAFznrNLk",
  31:"https://www.youtube.com/watch?v=46LmoouvP34",
  32:"https://www.youtube.com/watch?v=46LmoouvP34",
  33:"https://www.youtube.com/watch?v=AlTGQrDOd98",
  34:"https://www.youtube.com/watch?v=3OYSIWaJJk4",
  35:"https://www.youtube.com/watch?v=tzYip9kdVUU",
  36:"https://www.youtube.com/watch?v=46LmoouvP34",
  37:"https://www.youtube.com/watch?v=NaKsZos0bIY",
  38:"https://www.youtube.com/watch?v=_V0WOAL0_k0",
  39:"https://www.youtube.com/watch?v=cyihFNmsq-A",
  40:"https://www.youtube.com/watch?v=JcgLXCqSpKQ",
  41:"https://www.youtube.com/watch?v=5dJbeSf0_Vk",
  42:"https://www.youtube.com/watch?v=-wD7ThUxUn8",
  43:"https://www.youtube.com/watch?v=zGs04z2jIrk",
  44:"https://www.youtube.com/watch?v=iOeMmW3_l3s",
  45:"https://www.youtube.com/watch?v=iOeMmW3_l3s",
  46:"https://www.youtube.com/watch?v=iOeMmW3_l3s",
  47:"https://www.youtube.com/watch?v=NtaPROZOcmM",
  48:"https://www.youtube.com/watch?v=gfEyrmxbCbw",
  49:"https://www.youtube.com/watch?v=oHCxtt6g7UA",
  50:"https://www.youtube.com/watch?v=NtaPROZOcmM",
  51:"https://www.youtube.com/watch?v=cyihFNmsq-A",
  52:"https://www.youtube.com/watch?v=NtaPROZOcmM",
  53:"https://www.youtube.com/watch?v=0IOLRTdvzSM",
  54:"https://www.youtube.com/watch?v=0IOLRTdvzSM",
  55:"https://www.youtube.com/watch?v=ybNV36DoRfY",
  56:"https://www.youtube.com/watch?v=bLxb3w0c74w",
  57:"https://www.youtube.com/watch?v=NtaPROZOcmM",
  58:"https://www.youtube.com/watch?v=NtaPROZOcmM",
  59:"https://www.youtube.com/watch?v=6ffBlaBBWmA",
  60:"https://www.youtube.com/watch?v=6ffBlaBBWmA",
  61:"https://www.youtube.com/watch?v=6ffBlaBBWmA",
  62:"https://www.youtube.com/watch?v=6ffBlaBBWmA",
  63:"https://www.youtube.com/watch?v=_2xWmYNnFS8",
  64:"https://www.youtube.com/watch?v=C_lfM3v9HOc",
  65:"https://www.youtube.com/watch?v=C_lfM3v9HOc",
  66:"https://www.youtube.com/watch?v=ooP1Zq6lq5Y",
  67:"https://www.youtube.com/watch?v=kPugGvTvl1A",
  68:"https://www.youtube.com/watch?v=2LrjmwFDCFI",
  69:"https://www.youtube.com/watch?v=R4cYlVkcp7w",
  70:"https://www.youtube.com/watch?v=6ffBlaBBWmA",
  71:"https://www.youtube.com/watch?v=R4cYlVkcp7w",
  72:"https://www.youtube.com/watch?v=R4cYlVkcp7w",
  73:"https://www.youtube.com/watch?v=hXwBHRANfXU",
  74:"https://www.youtube.com/watch?v=nmMiarKvP1c",
  75:"https://www.youtube.com/watch?v=6ffBlaBBWmA",
  76:"https://www.youtube.com/watch?v=6ffBlaBBWmA",
  77:"https://www.youtube.com/watch?v=kPugGvTvl1A",
  78:"https://www.youtube.com/watch?v=j2uyKLS6GBE",
  79:"https://www.youtube.com/watch?v=ktdIgom5B18",
  80:"https://www.youtube.com/watch?v=EmSflSUgXro",
  81:"https://www.youtube.com/watch?v=EmSflSUgXro",
  82:"https://www.youtube.com/watch?v=EmSflSUgXro",
  83:"https://www.youtube.com/watch?v=DtSfBsdIlJo",
  84:"https://www.youtube.com/watch?v=DtSfBsdIlJo",
  85:"https://www.youtube.com/watch?v=DtSfBsdIlJo",
  86:"https://www.youtube.com/watch?v=kkDRsYBT6xs",
  87:"https://www.youtube.com/watch?v=PhNkkOieB-8",
  88:"https://www.youtube.com/watch?v=5DQnW7Cb-1k",
  89:"https://www.youtube.com/watch?v=5wUk8wQNUT8",
  90:"https://www.youtube.com/watch?v=5DQnW7Cb-1k",
  91:"https://www.youtube.com/watch?v=fR_yq6V4yxc",
  92:"https://www.youtube.com/watch?v=EmSflSUgXro",
  93:"https://www.youtube.com/watch?v=EmSflSUgXro",
  94:"https://www.youtube.com/watch?v=EmSflSUgXro",
  95:"https://www.youtube.com/watch?v=DU6dw6E1bzY",
  96:"https://www.youtube.com/watch?v=EmSflSUgXro",
  97:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  98:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  99:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  100:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  101:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  102:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  103:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  104:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  105:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  106:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  107:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  108:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  109:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  110:"https://www.youtube.com/watch?v=wwZmfFB9vrA",
  111:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  112:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  113:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  114:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  115:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  116:"https://www.youtube.com/watch?v=jz47v0Uj1cY",
  117:"https://www.youtube.com/watch?v=NaKsZos0bIY",
  118:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  119:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  120:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  121:"https://www.youtube.com/watch?v=wwZmfFB9vrA",
  122:"https://www.youtube.com/watch?v=wwZmfFB9vrA",
  123:"https://www.youtube.com/watch?v=wwZmfFB9vrA",
  124:"https://www.youtube.com/watch?v=wwZmfFB9vrA",
  125:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  126:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  127:"https://www.youtube.com/watch?v=_V0WOAL0_k0",
  128:"https://www.youtube.com/watch?v=NaKsZos0bIY",
  129:"https://www.youtube.com/watch?v=PXLF19Oqe3M",
  130:"https://www.youtube.com/watch?v=2QAy7DfDmgA",
  131:"https://www.youtube.com/watch?v=KIqRZEF_Aqg",
  132:"https://www.youtube.com/watch?v=l6OlwHmll3w",
  133:"https://www.youtube.com/watch?v=uej9usJAIUw",
  134:"https://www.youtube.com/watch?v=FVCmVLwRNe0",
  135:"https://www.youtube.com/watch?v=c9sY_1EXyvk",
  136:"https://www.youtube.com/watch?v=FVCmVLwRNe0",
  137:"https://www.youtube.com/watch?v=x9QWH_1AbP8",
  138:"https://www.youtube.com/watch?v=oXAMW-LNX_Q",
  139:"https://www.youtube.com/watch?v=ro1zBaXaOMg",
  140:"https://www.youtube.com/watch?v=U7p90HpfpQQ",
  141:"https://www.youtube.com/watch?v=b_lGhdrvac4",
  142:"https://www.youtube.com/watch?v=PXLF19Oqe3M",
  143:"https://www.youtube.com/watch?v=FVCmVLwRNe0",
  144:"https://www.youtube.com/watch?v=qjPN6ElNqpc",
  145:"https://www.youtube.com/watch?v=Yi_zNoIsNcc",
  146:"https://www.youtube.com/watch?v=a5rUdCeTtSE",
  147:"https://www.youtube.com/watch?v=RGqznhXhtJE",
  148:"https://www.youtube.com/watch?v=uutP0eBt51I",
  149:"https://www.youtube.com/watch?v=mIWCcAPizkw",
  150:"https://www.youtube.com/watch?v=Jvqe676qhmA",
  151:"https://www.youtube.com/watch?v=Y3CDzx-oj3k",
  152:"https://www.youtube.com/watch?v=mIWCcAPizkw",
  153:"https://www.youtube.com/watch?v=8cTohcawjCM",
  154:"https://www.youtube.com/watch?v=Jvqe676qhmA",
  155:"https://www.youtube.com/watch?v=Jvqe676qhmA",
  156:"https://www.youtube.com/watch?v=mIWCcAPizkw",
  157:"https://www.youtube.com/watch?v=Z64A_Q2aG3U",
  158:"https://www.youtube.com/watch?v=xyHLejrielo",
  159:"https://www.youtube.com/watch?v=5YNRp21YXw0",
  160:"https://www.youtube.com/watch?v=5YNRp21YXw0",
  161:"https://www.youtube.com/watch?v=yFsmmyJ9TmM",
  162:"https://www.youtube.com/watch?v=yFsmmyJ9TmM",
  163:"https://www.youtube.com/watch?v=wugNi3uEFUs",
  164:"https://www.youtube.com/watch?v=wugNi3uEFUs",
  165:"https://www.youtube.com/watch?v=xyHLejrielo",
  166:"https://www.youtube.com/watch?v=Z1DrxG0nSOU",
  167:"https://www.youtube.com/watch?v=t3IXE5JFPvI",
  168:"https://www.youtube.com/watch?v=jkH3WP_a_8E",
  169:"https://www.youtube.com/watch?v=6FONB2sSNQA",
  170:"https://www.youtube.com/watch?v=Iw2UhAot1gA",
  171:"https://www.youtube.com/watch?v=d2GgSoHvIXo",
  172:"https://www.youtube.com/watch?v=i0LN4UcCHUc",
  173:"https://www.youtube.com/watch?v=qXCtsKexOvQ",
  174:"https://www.youtube.com/watch?v=ZVas-oC00EA",
  175:"https://www.youtube.com/watch?v=-c39P9V64tU",
  176:"https://www.youtube.com/watch?v=i0LN4UcCHUc",
  177:"https://www.youtube.com/watch?v=PsBmNkba9yI",
  178:"https://www.youtube.com/watch?v=eskCgvDgu6w",
  179:"https://www.youtube.com/watch?v=1EG7z_qsYNY",
  180:"https://www.youtube.com/watch?v=1EG7z_qsYNY",
  181:"https://www.youtube.com/watch?v=LqJSszVWabw",
  182:"https://www.youtube.com/watch?v=LqJSszVWabw",
  183:"https://www.youtube.com/watch?v=JkTnzMJpgt4",
  184:"https://www.youtube.com/watch?v=LqJSszVWabw",
  185:"https://www.youtube.com/watch?v=NaKsZos0bIY",
  186:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  187:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  188:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  189:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  190:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  191:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  192:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  193:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  194:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  195:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  196:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  197:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  198:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  199:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  200:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  201:"https://www.youtube.com/watch?v=NaKsZos0bIY",
  202:"https://www.youtube.com/watch?v=KSugyYxzIjg",
  203:"https://www.youtube.com/watch?v=j_zWCP4a6tw",
  204:"https://www.youtube.com/watch?v=j_zWCP4a6tw",
  205:"https://www.youtube.com/watch?v=j_zWCP4a6tw",
  206:"https://www.youtube.com/watch?v=j_zWCP4a6tw",
  207:"https://www.youtube.com/watch?v=j_zWCP4a6tw",
  208:"https://www.youtube.com/watch?v=K4VAFznrNLk",
  209:"https://www.youtube.com/watch?v=j_zWCP4a6tw",
  210:"https://www.youtube.com/watch?v=NaKsZos0bIY",
  211:"https://www.youtube.com/watch?v=Maqi1i1tRQ0",
  212:"https://www.youtube.com/watch?v=_V0WOAL0_k0",
  213:"https://www.youtube.com/watch?v=j_zWCP4a6tw",
  214:"https://www.youtube.com/watch?v=5YNRp21YXw0",
  215:"https://www.youtube.com/watch?v=5YNRp21YXw0",
};

// ─────────────────────────────────────────────────────────────────────────────
// PROGRAMS
// ─────────────────────────────────────────────────────────────────────────────
const t = (session, slot, technique) => ({ session, slot, technique });

export const PROGRAMS = [
  { id:1, name:"Foundation",
    sessions:{
      C:{primary:{chestIso:9,chestComp:1},accessories:{back:34,triceps:147,biceps:131,forearms:157,neck:177,calves:167,coreFront:59}},
      D:{primary:{backIso:28,backComp:21},accessories:{chest:6,triceps:148,biceps:133,forearms:158,neck:178,calves:168,coreBack:42}},
      E:{primary:{triIso:144,triComp:149},accessories:{chest:3,back:33,biceps:130,forearms:163,neck:179,calves:169,coreSides:72}},
      F:{primary:{biIso:129,biComp:134},accessories:{chest:11,back:25,triceps:152,forearms:164,neck:180,calves:170,core:63}},
      G:{primary:{coreIso:62,coreComp:64},accessories:{chest:2,back:39,triceps:145,biceps:136,forearms:165,neck:181,calves:171}},
    },
    techniques:{
      week1:[t("C","chestComp","1_quarter_reps"),t("D","backComp","negative_accentuated")],
      week2:[t("E","triIso","super_slow"),t("F","biComp","drop_set")],
      week3:[t("G","coreIso","isometric_hold"),t("C","chestIso","rest_pause")],
      week4:[t("D","backIso","partials"),t("E","triComp","forced_reps")],
      week5:[t("F","biIso","mechanical_drop_set"),t("G","coreComp","pre_exhaustion")],
    },
  },
  { id:2, name:"Low-to-High",
    sessions:{
      C:{primary:{chestIso:10,chestComp:2},accessories:{back:33,triceps:148,biceps:133,forearms:158,neck:178,calves:168,coreFront:60}},
      D:{primary:{backIso:29,backComp:22},accessories:{chest:7,triceps:151,biceps:130,forearms:159,neck:179,calves:169,coreBack:71}},
      E:{primary:{triIso:145,triComp:150},accessories:{chest:4,back:34,biceps:132,forearms:164,neck:180,calves:170,coreSides:66}},
      F:{primary:{biIso:130,biComp:135},accessories:{chest:12,back:26,triceps:154,forearms:165,neck:181,calves:171,core:65}},
      G:{primary:{coreIso:61,coreComp:64},accessories:{chest:5,back:40,triceps:146,biceps:137,forearms:166,neck:182,calves:172}},
    },
    techniques:{
      week1:[t("C","chestIso","super_slow"),t("D","backComp","drop_set")],
      week2:[t("E","triComp","negative_accentuated"),t("F","biIso","isometric_hold")],
      week3:[t("G","coreComp","1_quarter_reps"),t("C","chestComp","rest_pause")],
      week4:[t("D","backIso","forced_reps"),t("E","triIso","partials")],
      week5:[t("F","biComp","pre_exhaustion"),t("G","coreIso","mechanical_drop_set")],
    },
  },
  { id:3, name:"High-to-Low",
    sessions:{
      C:{primary:{chestIso:11,chestComp:3},accessories:{back:22,triceps:151,biceps:132,forearms:159,neck:179,calves:169,coreFront:61}},
      D:{primary:{backIso:30,backComp:23},accessories:{chest:5,triceps:152,biceps:134,forearms:160,neck:180,calves:170,coreBack:75}},
      E:{primary:{triIso:146,triComp:153},accessories:{chest:8,back:35,biceps:129,forearms:161,neck:181,calves:171,coreSides:67}},
      F:{primary:{biIso:131,biComp:138},accessories:{chest:13,back:27,triceps:155,forearms:162,neck:182,calves:172,core:69}},
      G:{primary:{coreIso:75,coreComp:65},accessories:{chest:6,back:41,triceps:149,biceps:138,forearms:157,neck:183,calves:173}},
    },
    techniques:{
      week1:[t("D","backIso","isometric_hold"),t("E","triComp","1_quarter_reps")],
      week2:[t("F","biIso","super_slow"),t("G","coreComp","forced_reps")],
      week3:[t("C","chestComp","drop_set"),t("D","backComp","partials")],
      week4:[t("E","triIso","rest_pause"),t("F","biComp","mechanical_drop_set")],
      week5:[t("G","coreIso","negative_accentuated"),t("C","chestIso","pre_exhaustion")],
    },
  },
  { id:4, name:"Single-Arm Focus",
    sessions:{
      C:{primary:{chestIso:12,chestComp:4},accessories:{back:21,triceps:152,biceps:133,forearms:160,neck:180,calves:170,coreFront:62}},
      D:{primary:{backIso:33,backComp:24},accessories:{chest:8,triceps:154,biceps:132,forearms:161,neck:181,calves:171,coreBack:69}},
      E:{primary:{triIso:147,triComp:149},accessories:{chest:6,back:28,biceps:135,forearms:162,neck:182,calves:172,coreSides:68}},
      F:{primary:{biIso:132,biComp:139},accessories:{chest:14,back:23,triceps:156,forearms:163,neck:183,calves:173,core:70}},
      G:{primary:{coreIso:59,coreComp:66},accessories:{chest:9,back:29,triceps:150,biceps:140,forearms:164,neck:184,calves:174}},
    },
    techniques:{
      week1:[t("E","triIso","partials"),t("F","biComp","1_quarter_reps")],
      week2:[t("G","coreComp","super_slow"),t("C","chestComp","isometric_hold")],
      week3:[t("D","backComp","rest_pause"),t("E","triComp","drop_set")],
      week4:[t("F","biIso","negative_accentuated"),t("G","coreIso","forced_reps")],
      week5:[t("C","chestIso","mechanical_drop_set"),t("D","backIso","pre_exhaustion")],
    },
  },
  { id:5, name:"Overhead Emphasis",
    sessions:{
      C:{primary:{chestIso:13,chestComp:5},accessories:{back:39,triceps:154,biceps:131,forearms:161,neck:181,calves:171,coreFront:69}},
      D:{primary:{backIso:34,backComp:25},accessories:{chest:14,triceps:155,biceps:131,forearms:162,neck:182,calves:172,coreBack:76}},
      E:{primary:{triIso:148,triComp:150},accessories:{chest:1,back:36,biceps:133,forearms:163,neck:183,calves:173,coreSides:74}},
      F:{primary:{biIso:133,biComp:142},accessories:{chest:15,back:31,triceps:144,forearms:164,neck:184,calves:174,core:73}},
      G:{primary:{coreIso:71,coreComp:67},accessories:{chest:10,back:42,triceps:148,biceps:141,forearms:165,neck:177,calves:175}},
    },
    techniques:{
      week1:[t("F","biIso","forced_reps"),t("G","coreComp","partials")],
      week2:[t("C","chestIso","1_quarter_reps"),t("D","backComp","super_slow")],
      week3:[t("E","triIso","mechanical_drop_set"),t("F","biComp","rest_pause")],
      week4:[t("G","coreIso","isometric_hold"),t("C","chestComp","drop_set")],
      week5:[t("D","backIso","negative_accentuated"),t("E","triComp","pre_exhaustion")],
    },
  },
  { id:6, name:"Squeeze & Contract",
    sessions:{
      C:{primary:{chestIso:16,chestComp:6},accessories:{back:28,triceps:155,biceps:129,forearms:162,neck:182,calves:172,coreFront:70}},
      D:{primary:{backIso:35,backComp:26},accessories:{chest:15,triceps:156,biceps:136,forearms:163,neck:183,calves:173,coreBack:73}},
      E:{primary:{triIso:151,triComp:153},accessories:{chest:2,back:37,biceps:134,forearms:164,neck:184,calves:174,coreSides:77}},
      F:{primary:{biIso:136,biComp:134},accessories:{chest:16,back:32,triceps:147,forearms:165,neck:177,calves:175,core:76}},
      G:{primary:{coreIso:72,coreComp:68},accessories:{chest:11,back:30,triceps:145,biceps:129,forearms:166,neck:178,calves:176}},
    },
    techniques:{
      week1:[t("G","coreIso","pre_exhaustion"),t("C","chestComp","mechanical_drop_set")],
      week2:[t("D","backIso","1_quarter_reps"),t("E","triIso","drop_set")],
      week3:[t("F","biIso","forced_reps"),t("G","coreComp","super_slow")],
      week4:[t("C","chestIso","isometric_hold"),t("D","backComp","rest_pause")],
      week5:[t("E","triComp","negative_accentuated"),t("F","biComp","partials")],
    },
  },
  { id:7, name:"Unilateral Drive",
    sessions:{
      C:{primary:{chestIso:18,chestComp:7},accessories:{back:25,triceps:156,biceps:130,forearms:163,neck:183,calves:173,coreFront:71}},
      D:{primary:{backIso:39,backComp:27},accessories:{chest:17,triceps:144,biceps:137,forearms:164,neck:184,calves:174,coreBack:74}},
      E:{primary:{triIso:152,triComp:149},accessories:{chest:9,back:38,biceps:140,forearms:165,neck:177,calves:175,coreSides:63}},
      F:{primary:{biIso:137,biComp:135},accessories:{chest:17,back:22,triceps:148,forearms:166,neck:178,calves:176,core:77}},
      G:{primary:{coreIso:62,coreComp:69},accessories:{chest:12,back:33,triceps:150,biceps:142,forearms:157,neck:179,calves:167}},
    },
    techniques:{
      week1:[t("C","chestComp","drop_set"),t("D","backIso","super_slow")],
      week2:[t("E","triIso","1_quarter_reps"),t("F","biIso","negative_accentuated")],
      week3:[t("G","coreComp","rest_pause"),t("C","chestIso","forced_reps")],
      week4:[t("D","backComp","mechanical_drop_set"),t("E","triComp","isometric_hold")],
      week5:[t("F","biComp","partials"),t("G","coreIso","pre_exhaustion")],
    },
  },
  { id:8, name:"Tempo & Control",
    sessions:{
      C:{primary:{chestIso:9,chestComp:8},accessories:{back:35,triceps:144,biceps:131,forearms:164,neck:184,calves:174,coreFront:76}},
      D:{primary:{backIso:40,backComp:31},accessories:{chest:19,triceps:147,biceps:131,forearms:165,neck:177,calves:175,coreBack:42}},
      E:{primary:{triIso:154,triComp:150},accessories:{chest:10,back:21,biceps:143,forearms:166,neck:178,calves:176,coreSides:64}},
      F:{primary:{biIso:140,biComp:138},accessories:{chest:18,back:34,triceps:146,forearms:157,neck:179,calves:167,core:59}},
      G:{primary:{coreIso:60,coreComp:70},accessories:{chest:13,back:26,triceps:153,biceps:129,forearms:158,neck:180,calves:168}},
    },
    techniques:{
      week1:[t("E","triComp","super_slow"),t("F","biComp","1_quarter_reps")],
      week2:[t("G","coreIso","drop_set"),t("C","chestIso","isometric_hold")],
      week3:[t("D","backComp","forced_reps"),t("E","triIso","partials")],
      week4:[t("F","biIso","pre_exhaustion"),t("G","coreComp","negative_accentuated")],
      week5:[t("C","chestComp","rest_pause"),t("D","backIso","mechanical_drop_set")],
    },
  },
  { id:9, name:"Rotation & Reach",
    sessions:{
      C:{primary:{chestIso:10,chestComp:14},accessories:{back:26,triceps:145,biceps:130,forearms:165,neck:177,calves:175,coreFront:60}},
      D:{primary:{backIso:41,backComp:32},accessories:{chest:20,triceps:148,biceps:130,forearms:166,neck:178,calves:176,coreBack:69}},
      E:{primary:{triIso:155,triComp:153},accessories:{chest:11,back:22,biceps:141,forearms:157,neck:179,calves:167,coreSides:65}},
      F:{primary:{biIso:141,biComp:139},accessories:{chest:19,back:35,triceps:149,forearms:158,neck:180,calves:168,core:61}},
      G:{primary:{coreIso:61,coreComp:73},accessories:{chest:1,back:27,triceps:155,biceps:135,forearms:159,neck:181,calves:169}},
    },
    techniques:{
      week1:[t("F","biIso","rest_pause"),t("G","coreComp","partials")],
      week2:[t("C","chestComp","pre_exhaustion"),t("D","backIso","1_quarter_reps")],
      week3:[t("E","triIso","super_slow"),t("F","biComp","forced_reps")],
      week4:[t("G","coreIso","drop_set"),t("C","chestIso","negative_accentuated")],
      week5:[t("D","backComp","isometric_hold"),t("E","triComp","mechanical_drop_set")],
    },
  },
  { id:10, name:"Full-Range Strength",
    sessions:{
      C:{primary:{chestIso:11,chestComp:15},accessories:{back:24,triceps:146,biceps:131,forearms:166,neck:178,calves:176,coreFront:61}},
      D:{primary:{backIso:42,backComp:36},accessories:{chest:1,triceps:149,biceps:129,forearms:157,neck:179,calves:167,coreBack:75}},
      E:{primary:{triIso:156,triComp:149},accessories:{chest:12,back:23,biceps:142,forearms:158,neck:180,calves:168,coreSides:72}},
      F:{primary:{biIso:143,biComp:142},accessories:{chest:20,back:36,triceps:151,forearms:159,neck:181,calves:169,core:62}},
      G:{primary:{coreIso:62,coreComp:74},accessories:{chest:2,back:28,triceps:156,biceps:136,forearms:160,neck:182,calves:170}},
    },
    techniques:{
      week1:[t("G","coreComp","negative_accentuated"),t("C","chestIso","partials")],
      week2:[t("D","backComp","pre_exhaustion"),t("E","triComp","drop_set")],
      week3:[t("F","biComp","super_slow"),t("G","coreIso","rest_pause")],
      week4:[t("C","chestComp","forced_reps"),t("D","backIso","isometric_hold")],
      week5:[t("E","triIso","1_quarter_reps"),t("F","biIso","mechanical_drop_set")],
    },
  },
  { id:11, name:"Stretch & Contract",
    sessions:{
      C:{primary:{chestIso:12,chestComp:17},accessories:{back:27,triceps:147,biceps:130,forearms:157,neck:179,calves:167,coreFront:62}},
      D:{primary:{backIso:28,backComp:37},accessories:{chest:2,triceps:150,biceps:141,forearms:158,neck:180,calves:168,coreBack:76}},
      E:{primary:{triIso:144,triComp:150},accessories:{chest:13,back:24,biceps:143,forearms:159,neck:181,calves:169,coreSides:73}},
      F:{primary:{biIso:129,biComp:134},accessories:{chest:3,back:29,triceps:152,forearms:160,neck:182,calves:170,core:71}},
      G:{primary:{coreIso:59,coreComp:76},accessories:{chest:4,back:37,triceps:145,biceps:137,forearms:161,neck:183,calves:171}},
    },
    techniques:{
      week1:[t("C","chestComp","isometric_hold"),t("D","backIso","drop_set")],
      week2:[t("E","triIso","mechanical_drop_set"),t("F","biComp","super_slow")],
      week3:[t("G","coreIso","1_quarter_reps"),t("C","chestIso","forced_reps")],
      week4:[t("D","backComp","partials"),t("E","triComp","rest_pause")],
      week5:[t("F","biIso","pre_exhaustion"),t("G","coreComp","negative_accentuated")],
    },
  },
  { id:12, name:"Peak Intensity",
    sessions:{
      C:{primary:{chestIso:13,chestComp:19},accessories:{back:29,triceps:148,biceps:133,forearms:158,neck:180,calves:168,coreFront:69}},
      D:{primary:{backIso:30,backComp:38},accessories:{chest:3,triceps:151,biceps:143,forearms:159,neck:181,calves:169,coreBack:42}},
      E:{primary:{triIso:145,triComp:153},accessories:{chest:14,back:40,biceps:139,forearms:160,neck:182,calves:170,coreSides:64}},
      F:{primary:{biIso:130,biComp:135},accessories:{chest:4,back:41,triceps:154,forearms:161,neck:183,calves:171,core:75}},
      G:{primary:{coreIso:71,coreComp:77},accessories:{chest:15,back:38,triceps:146,biceps:134,forearms:162,neck:184,calves:172}},
    },
    techniques:{
      week1:[t("D","backComp","1_quarter_reps"),t("E","triIso","pre_exhaustion")],
      week2:[t("F","biComp","negative_accentuated"),t("G","coreComp","isometric_hold")],
      week3:[t("C","chestIso","super_slow"),t("D","backIso","forced_reps")],
      week4:[t("E","triComp","drop_set"),t("F","biIso","rest_pause")],
      week5:[t("G","coreIso","mechanical_drop_set"),t("C","chestComp","partials")],
    },
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// LOOKUP HELPERS
// ─────────────────────────────────────────────────────────────────────────────
export const SESSION_FOCUS = {
  C:{label:"CHEST DAY",   color:"#00d4ff"},
  D:{label:"BACK DAY",    color:"#22c55e"},
  E:{label:"TRICEPS DAY", color:"#f59e0b"},
  F:{label:"BICEPS DAY",  color:"#f97316"},
  G:{label:"CORE DAY",    color:"#ec4899"},
};

export const SLOT_LABELS = {
  chestIso:"Chest ISO", chestComp:"Chest CMP",
  backIso:"Back ISO",   backComp:"Back CMP",
  triIso:"Tri ISO",     triComp:"Tri CMP",
  biIso:"Bi ISO",       biComp:"Bi CMP",
  coreIso:"Core ISO",   coreComp:"Core CMP",
  back:"Back", chest:"Chest", triceps:"Triceps", biceps:"Biceps",
  forearms:"Forearms", neck:"Neck", calves:"Calves",
  coreFront:"Core Front", coreBack:"Core Back",
  coreSides:"Core Sides", core:"Core",
};

export const exGroup = (id) => {
  if (id<=20)  return {label:"CHEST",     color:"#00d4ff"};
  if (id<=42)  return {label:"BACK",      color:"#22c55e"};
  if (id<=58)  return {label:"SHOULDERS", color:"#60a5fa"};
  if (id<=77)  return {label:"CORE",      color:"#ec4899"};
  if (id<=96)  return {label:"GLUTES",    color:"#c084fc"};
  if (id<=116) return {label:"QUADS",     color:"#f97316"};
  if (id<=128) return {label:"HAMSTRINGS",color:"#fb923c"};
  if (id<=143) return {label:"BICEPS",    color:"#4ade80"};
  if (id<=156) return {label:"TRICEPS",   color:"#f59e0b"};
  if (id<=166) return {label:"FOREARMS",  color:"#94a3b8"};
  if (id<=176) return {label:"CALVES",    color:"#38bdf8"};
  if (id<=184) return {label:"NECK",      color:"#f87171"};
  if (id<=202) return {label:"FULL BODY", color:"#00d4ff"};
  return              {label:"MOBILITY",  color:"#86efac"};
};

export const ALL_GROUPS = ["All","CHEST","BACK","SHOULDERS","CORE","GLUTES","QUADS",
  "HAMSTRINGS","BICEPS","TRICEPS","FOREARMS","CALVES","NECK","FULL BODY","MOBILITY"];

// ─────────────────────────────────────────────────────────────────────────────
// BANDS — 103 bands, 6 brands
// ─────────────────────────────────────────────────────────────────────────────
export const BANDS = [
  {id:"b0",  brand:"Serious Steel",color:"Orange",    model:"#0",        lengthIn:12,res:"2-15"},
  {id:"b1",  brand:"Serious Steel",color:"Purple",    model:"#1",        lengthIn:12,res:"5-35"},
  {id:"b2",  brand:"Serious Steel",color:"Red",       model:"#2",        lengthIn:12,res:"10-50"},
  {id:"b3",  brand:"Serious Steel",color:"Blue",      model:"#3",        lengthIn:12,res:"25-80"},
  {id:"b4",  brand:"Serious Steel",color:"Green",     model:"#4",        lengthIn:12,res:"50-120"},
  {id:"b5",  brand:"Serious Steel",color:"Purple",    model:"#1",        lengthIn:20,res:"10-25"},
  {id:"b6",  brand:"Serious Steel",color:"Red",       model:"#2",        lengthIn:20,res:"15-40"},
  {id:"b7",  brand:"Serious Steel",color:"Blue",      model:"#3",        lengthIn:20,res:"20-50"},
  {id:"b8",  brand:"Serious Steel",color:"Green",     model:"#4",        lengthIn:20,res:"40-100"},
  {id:"b9",  brand:"Serious Steel",color:"Black",     model:"#5",        lengthIn:20,res:"55-140"},
  {id:"b10", brand:"Serious Steel",color:"Orange",    model:"#0",        lengthIn:32,res:"2-15"},
  {id:"b11", brand:"Serious Steel",color:"Purple",    model:"#1",        lengthIn:32,res:"5-35"},
  {id:"b12", brand:"Serious Steel",color:"Red",       model:"#2",        lengthIn:32,res:"10-50"},
  {id:"b13", brand:"Serious Steel",color:"Blue",      model:"#3",        lengthIn:32,res:"25-80"},
  {id:"b14", brand:"Serious Steel",color:"Green",     model:"#4",        lengthIn:32,res:"50-120"},
  {id:"b15", brand:"Serious Steel",color:"Black",     model:"#5",        lengthIn:32,res:"60-150"},
  {id:"b16", brand:"Serious Steel",color:"Yellow",    model:"#6",        lengthIn:32,res:"80-200"},
  {id:"b17", brand:"Serious Steel",color:"Gray",      model:"#6.5",      lengthIn:32,res:"115-290"},
  {id:"b18", brand:"Serious Steel",color:"Orange",    model:"#0",        lengthIn:37,res:"2-15"},
  {id:"b19", brand:"Serious Steel",color:"Purple",    model:"#1",        lengthIn:37,res:"5-35"},
  {id:"b20", brand:"Serious Steel",color:"Red",       model:"#2",        lengthIn:37,res:"10-50"},
  {id:"b21", brand:"Serious Steel",color:"Blue",      model:"#3",        lengthIn:37,res:"25-80"},
  {id:"b22", brand:"Serious Steel",color:"Green",     model:"#4",        lengthIn:37,res:"50-120"},
  {id:"b23", brand:"Serious Steel",color:"Black",     model:"#5",        lengthIn:37,res:"60-150"},
  {id:"b24", brand:"Serious Steel",color:"Yellow",    model:"#6",        lengthIn:37,res:"80-200"},
  {id:"b25", brand:"Serious Steel",color:"Gray",      model:"#6.5",      lengthIn:37,res:"115-290"},
  {id:"b26", brand:"Serious Steel",color:"Orange",    model:"#0",        lengthIn:41,res:"2-15"},
  {id:"b27", brand:"Serious Steel",color:"Purple",    model:"#1",        lengthIn:41,res:"5-35"},
  {id:"b28", brand:"Serious Steel",color:"Red",       model:"#2",        lengthIn:41,res:"10-50"},
  {id:"b29", brand:"Serious Steel",color:"Blue",      model:"#3",        lengthIn:41,res:"25-80"},
  {id:"b30", brand:"Serious Steel",color:"Green",     model:"#4",        lengthIn:41,res:"50-120"},
  {id:"b31", brand:"Serious Steel",color:"Black",     model:"#5",        lengthIn:41,res:"60-150"},
  {id:"b32", brand:"Serious Steel",color:"Yellow",    model:"#6",        lengthIn:41,res:"80-200"},
  {id:"b33", brand:"Serious Steel",color:"Gray",      model:"#6.5",      lengthIn:41,res:"115-290"},
  {id:"b34", brand:"Serious Steel",color:"Orange",    model:"#7 Mega",   lengthIn:41,res:"120-300+"},
  {id:"b35", brand:"Harambe",      color:"Yellow",    model:"1/4in wide",lengthIn:38,res:"10-20"},
  {id:"b36", brand:"Harambe",      color:"White",     model:"1/2in wide",lengthIn:38,res:"20-40"},
  {id:"b37", brand:"Harambe",      color:"Lt Green",  model:"1in wide",  lengthIn:38,res:"40-80"},
  {id:"b38", brand:"Harambe",      color:"Hvy Green", model:"2in wide",  lengthIn:38,res:"80-160"},
  {id:"b39", brand:"Harambe",      color:"Black",     model:"2.5in wide",lengthIn:38,res:"100-200"},
  {id:"b103",brand:"Harambe",      color:"Orange",    model:"Deficit 1/4in",lengthIn:38,res:"5-10"},
  {id:"b40", brand:"X3",           color:"White UL",  model:"Ultra Light",lengthIn:41,res:"<10-30"},
  {id:"b41", brand:"X3",           color:"White",     model:"Standard",  lengthIn:41,res:"10-50+"},
  {id:"b42", brand:"X3",           color:"Lt Grey",   model:"Standard",  lengthIn:41,res:"25-80+"},
  {id:"b43", brand:"X3",           color:"Dk Grey",   model:"Standard",  lengthIn:41,res:"50-120+"},
  {id:"b44", brand:"X3",           color:"Black",     model:"Standard",  lengthIn:41,res:"60-150+"},
  {id:"b45", brand:"X3",           color:"Orange",    model:"Elite",     lengthIn:41,res:"110-300+"},
  {id:"b104",brand:"X3",           color:"Orange",    model:"PF Gen2 Elite",   lengthIn:41,res:"120-300+"},
  {id:"b105",brand:"X3",           color:"Orange",    model:"PF Gen2 UL",      lengthIn:41,res:"<5-20"},
  {id:"b46", brand:"X3",           color:"White",     model:"Short Set", lengthIn:34,res:"10-50+"},
  {id:"b47", brand:"X3",           color:"Lt Grey",   model:"Short Set", lengthIn:34,res:"25-80+"},
  {id:"b48", brand:"X3",           color:"Dk Grey",   model:"Short Set", lengthIn:34,res:"50-120+"},
  {id:"b49", brand:"X3",           color:"Black",     model:"Short Set", lengthIn:34,res:"60-150+"},
  {id:"b50", brand:"X3",           color:"White UL",  model:"Gen2 Perf", lengthIn:41,res:"<10-30"},
  {id:"b51", brand:"X3",           color:"White",     model:"Gen2 Perf", lengthIn:41,res:"10-50+"},
  {id:"b52", brand:"X3",           color:"Lt Grey",   model:"Gen2 Perf", lengthIn:41,res:"25-80+"},
  {id:"b53", brand:"X3",           color:"Dk Grey",   model:"Gen2 Perf", lengthIn:41,res:"50-120+"},
  {id:"b54", brand:"X3",           color:"Black",     model:"Gen2 Perf", lengthIn:41,res:"60-150+"},
  {id:"b55", brand:"Clench",       color:"Orange",    model:"Light",     lengthIn:34,res:"5-15"},
  {id:"b56", brand:"Clench",       color:"Red",       model:"Light",     lengthIn:34,res:"15-35"},
  {id:"b57", brand:"Clench",       color:"Black",     model:"Medium",    lengthIn:34,res:"35-75"},
  {id:"b58", brand:"Clench",       color:"Purple",    model:"Heavy",     lengthIn:34,res:"50-100"},
  {id:"b59", brand:"Clench",       color:"Green",     model:"XH",        lengthIn:34,res:"75-150"},
  {id:"b60", brand:"Clench",       color:"Blue",      model:"XXH",       lengthIn:34,res:"90-230"},
  {id:"b61", brand:"Clench",       color:"Org Heavy", model:"Monster",   lengthIn:34,res:"110-300"},
  {id:"b62", brand:"Clench",       color:"Grey",      model:"Mega",      lengthIn:34,res:"150-400"},
  {id:"b63", brand:"Clench",       color:"Orange",    model:"Light",     lengthIn:41,res:"5-15"},
  {id:"b64", brand:"Clench",       color:"Red",       model:"Light",     lengthIn:41,res:"15-35"},
  {id:"b65", brand:"Clench",       color:"Black",     model:"Medium",    lengthIn:41,res:"35-75"},
  {id:"b66", brand:"Clench",       color:"Purple",    model:"Heavy",     lengthIn:41,res:"50-100"},
  {id:"b67", brand:"Clench",       color:"Green",     model:"XH",        lengthIn:41,res:"75-150"},
  {id:"b68", brand:"Clench",       color:"Blue",      model:"XXH",       lengthIn:41,res:"90-230"},
  {id:"b69", brand:"Clench",       color:"Org Heavy", model:"Monster",   lengthIn:41,res:"110-300"},
  {id:"b70", brand:"Clench",       color:"Grey",      model:"Mega",      lengthIn:41,res:"150-400"},
  {id:"b71", brand:"Quantum",      color:"Orange",    model:"Micro",      lengthIn:13,res:"5-30"},
  {id:"b72", brand:"Quantum",      color:"Yellow",    model:"Super Micro",lengthIn:13,res:"10-40"},
  {id:"b73", brand:"Quantum",      color:"Red",       model:"Mini",       lengthIn:13,res:"15-55"},
  {id:"b74", brand:"Quantum",      color:"Orange",    model:"Micro",      lengthIn:41,res:"5-30"},
  {id:"b75", brand:"Quantum",      color:"Yellow",    model:"Super Micro",lengthIn:41,res:"10-40"},
  {id:"b76", brand:"Quantum",      color:"Red",       model:"Mini",       lengthIn:41,res:"15-55"},
  {id:"b77", brand:"Quantum",      color:"Black",     model:"Medium",     lengthIn:41,res:"20-85"},
  {id:"b78", brand:"Quantum",      color:"Purple",    model:"Large",      lengthIn:41,res:"30-115"},
  {id:"b79", brand:"Quantum",      color:"Green",     model:"XL",         lengthIn:41,res:"40-180"},
  {id:"b80", brand:"Quantum",      color:"Blue",      model:"XXL",        lengthIn:41,res:"65-230"},
  {id:"b81", brand:"Quantum",      color:"Gray",      model:"XXXL",       lengthIn:41,res:"110-300"},
  {id:"b82", brand:"Quantum",      color:"Black",     model:"Mega",       lengthIn:41,res:"150-400"},
  {id:"b83", brand:"Quantum",      color:"Orange",    model:"Thunder",   lengthIn:73,res:"5-30"},
  {id:"b84", brand:"Quantum",      color:"Yellow",    model:"Thunder",   lengthIn:73,res:"10-40"},
  {id:"b85", brand:"Quantum",      color:"Red",       model:"Thunder",   lengthIn:73,res:"15-55"},
  {id:"b86", brand:"Quantum",      color:"Black",     model:"Thunder",   lengthIn:73,res:"20-85"},
  {id:"b87", brand:"Quantum",      color:"Purple",    model:"Thunder",   lengthIn:73,res:"30-115"},
  {id:"b88", brand:"Quantum",      color:"Green",     model:"Thunder",   lengthIn:73,res:"40-180"},
  {id:"b89", brand:"Quantum",      color:"Blue",      model:"Thunder",   lengthIn:73,res:"65-230"},
  {id:"b90", brand:"Quantum",      color:"Gray",      model:"Thunder",   lengthIn:73,res:"110-300"},
  {id:"b91", brand:"HeavyDutyBar", color:"Yellow",    model:"PO 1/4in",  lengthIn:41,res:"~5-25"},
  {id:"b92", brand:"HeavyDutyBar", color:"Red",       model:"PO 1/2in",  lengthIn:41,res:"~15-50"},
  {id:"b93", brand:"HeavyDutyBar", color:"Blue",      model:"PO 1-1/8in",lengthIn:41,res:"~30-90"},
  {id:"b94", brand:"HeavyDutyBar", color:"Black",     model:"PO 1-3/4in",lengthIn:41,res:"~55-130"},
  {id:"b95", brand:"HeavyDutyBar", color:"Green",     model:"PO 3-1/4in",lengthIn:41,res:"~90-200"},
  {id:"b96", brand:"HeavyDutyBar", color:"White",     model:"PO 4in",    lengthIn:41,res:"~120-300+"},
  {id:"b97", brand:"HeavyDutyBar", color:"Purple",    model:"Monster",   lengthIn:38,res:"~65-160"},
  {id:"b98", brand:"HeavyDutyBar", color:"Yellow",    model:"Travel",    lengthIn:41,res:"~5-20"},
  {id:"b99", brand:"HeavyDutyBar", color:"Red",       model:"Travel",    lengthIn:41,res:"~10-35"},
  {id:"b100",brand:"HeavyDutyBar", color:"Black",     model:"Travel",    lengthIn:41,res:"~25-70"},
  {id:"b101",brand:"HeavyDutyBar", color:"Purple",    model:"Travel",    lengthIn:41,res:"~40-100"},
  {id:"b102",brand:"HeavyDutyBar", color:"Green",     model:"Travel",    lengthIn:41,res:"~60-150"},
];

export const COLOR_HEX = {
  "Orange":"#f97316","Purple":"#a855f7","Red":"#ef4444","Blue":"#3b82f6",
  "Green":"#22c55e","Black":"#4b5563","Yellow":"#eab308","Gray":"#9ca3af",
  "Grey":"#9ca3af","White":"#f1f5f9","Lt Grey":"#d1d5db","Dk Grey":"#6b7280",
  "Lt Green":"#86efac","Hvy Green":"#15803d","Org Heavy":"#ea580c",
  "White UL":"#ecfdf5",
};

export const BAND_BRANDS = ["All","Serious Steel","Harambe","X3","Clench","Quantum","HeavyDutyBar"];

// ─────────────────────────────────────────────────────────────────────────────
// GEAR INVENTORY
// ─────────────────────────────────────────────────────────────────────────────
export const GEAR = [
  { brand:"Harambe", items:[
    {name:"T Bar",qty:1,status:"owned"},{name:"Cyberplate",qty:1,status:"owned"},
    {name:"Handles",qty:2,status:"owned"},{name:"Rods",qty:2,status:"owned"},
    {name:"Black Ropes",qty:1,status:"owned",note:"set"},{name:"White Ropes",qty:1,status:"owned",note:"set"},
    {name:"Split Squat Belt",qty:1,status:"owned"},{name:"Wedges",qty:2,status:"owned"},
    {name:"Foam Block",qty:1,status:"owned"},
  ]},
  { brand:"X3 Bar", items:[
    {name:"Steel Ground Plate",qty:1,status:"owned"},{name:"Squat Belt (Medium)",qty:1,status:"owned"},
    {name:"Elite Bar",qty:1,status:"owned"},{name:"Force Bar",qty:1,status:"owned"},
  ]},
  { brand:"Clench", items:[
    {name:"Carbon Pro Bar",qty:1,status:"owned"},{name:"Handles",qty:2,status:"owned"},
    {name:"Heavy Duty Anchors",qty:2,status:"owned"},{name:"Footplate",qty:1,status:"owned"},
    {name:"Carbon EZ Bar",qty:1,status:"preorder",note:"In transit"},
  ]},
  { brand:"Serious Steel", items:[
    {name:"Acacia Training Platform",qty:1,status:"owned"},{name:"Wrist Wraps",qty:2,status:"owned",note:"pairs"},
    {name:"Door Anchor",qty:1,status:"owned"},{name:"Large Band Guard",qty:1,status:"owned"},
  ]},
  { brand:"HeavyDutyBar", items:[
    {name:"Bantam Bar",qty:1,status:"owned"},{name:"Qlaw Handles",qty:2,status:"owned"},
    {name:"Qdeck",qty:1,status:"preorder",note:"In transit"},{name:"Tension Master",qty:1,status:"owned",note:"PO"},
    {name:"Elevators",qty:2,status:"owned"},
  ]},
];

// ─────────────────────────────────────────────────────────────────────────────
// SCHEDULE HELPERS
// ─────────────────────────────────────────────────────────────────────────────
export const SCHED_DAYS = { MWF:[1,3,5], TTS:[2,4,6] };

export function countWkDays(startStr, days, upTo) {
  const s = new Date(startStr + "T00:00:00");
  const e = new Date(upTo); e.setHours(0,0,0,0);
  let n = 0;
  const d = new Date(s);
  while (d <= e) {
    if (days.includes(d.getDay())) n++;
    d.setDate(d.getDate()+1);
  }
  return n;
}

export function nextWkDay(from, days) {
  const d = new Date(from);
  for (let i=1; i<=7; i++) {
    d.setDate(d.getDate()+1);
    if (days.includes(d.getDay())) return new Date(d);
  }
}

export function calcToday(startStr, sched, pi) {
  const days = SCHED_DAYS[sched];
  const today = new Date(); today.setHours(0,0,0,0);
  const isWk = days.includes(today.getDay());
  if (isWk) {
    const n = countWkDays(startStr, days, today);
    const idx = n - 1;
    return { isWk:true, session:["C","D","E","F","G"][idx%5],
             week:Math.min(Math.floor(idx/3)+1,6), num:n, prog:PROGRAMS[pi] };
  } else {
    const next = nextWkDay(today, days);
    const n2 = countWkDays(startStr, days, next);
    const idx2 = n2 - 1;
    return { isWk:false, nextDate:next, session:["C","D","E","F","G"][idx2%5],
             week:Math.min(Math.floor(idx2/3)+1,6), prog:PROGRAMS[pi] };
  }
}

export const PROG_REPS = 12;
